### ISSUE TITLE
make responsive (mobile first)

### ISSUE THREAD

**Issue by serapath** [playproject-io/play-ed#10]
## `@todo`
* [ ] make responsive (mobile first)
* [ ] create medium article with play embedded
* [ ] generate workshop with embedded play-ed to document play-ed features
* [ ] full screen button on every element when in focus (chat, editor with preview, just editor, just preview, tasks etc.)

---
