### ISSUE TITLE
add solidity syntax highlighting for codemirror

### ISSUE THREAD

**Issue by serapath** [playproject-io/play-ed#13]
## `@todo`
* [ ] syntax highlighting solidity (code mirror 5 & code mirror 6 compatible)
  * for details check: [google docs todo list](https://docs.google.com/spreadsheets/d/1xEGdDAK-2_dKgGZbkieaWAfOkNd-LYA07t3llkAmFYI/edit?usp=sharing)
  * https://gitter.im/ethereum/play?at=5cbfe09c97dcb371d8031305
* [ ] integrate syntax highlighting into editor yet,
    * https://alincode.github.io/codemirror-solidity/
* [ ] integrate into https://carbon.now.sh/

---
**results:**
* https://github.com/alincode/CodeMirror

**resources:**
* https://github.com/ethereum/remix-ide/pull/1415
* https://www.npmjs.com/package/ace-mode-solidity
* https://github.com/raphaelhuefner/ace-mode-solidity
* https://github.com/raphaelhuefner/ace-mode-solidity/blob/master/lib/ace/mode/solidity_highlight_rules.js
* https://github.com/raphaelhuefner/ace-mode-solidity/blob/master/lib/ace/mode/solidity.js
* https://www.raymondcamden.com/2018/06/18/my-first-stab-at-a-grammar-extension-for-vs-code

got some inspiration and wonder if it makes sense to have scope highlighting in solidity.
Don't know the exact scoping rules of solidity yet i have to say, but here is the link:
* https://github.com/daniellmb/JavaScript-Scope-Context-Coloring

todo list:

https://docs.google.com/spreadsheets/d/1xEGdDAK-2_dKgGZbkieaWAfOkNd-LYA07t3llkAmFYI/edit?usp=sharing

code:

https://github.com/alincode/CodeMirror

https://alincode.github.io/codemirror-solidity/
https://www.npmjs.com/package/codemirror-solidity
