### ISSUE TITLE
enable switching command/package versions

### ISSUE THREAD

**Issue by serapath** [playproject-io/play-ed#14]
## `@todo`
* [ ] auto-select latest or given default/custom/configured version on load
    * e.g. thinkg "solc-js pragma" but also default versions for old files with no pragma
* [ ] notify user about new versions and (auto)update
* [ ] enable switching command/package versions (maybe with a dropdown menu)
* [ ] add UI for selecting command/package version and command/package action button
* [ ] indicate downloaded/cached command/package (maybe with option to "download & cache ...all/nightly/release")
* [ ] integrate `solc-js` as a proof of concept command/package

---
