### ISSUE TITLE
play-ed concept & updates

### ISSUE THREAD

**Issue by serapath** [playproject-io/play-ed#2]
## `@todo`
* [x] [`play-ed#15`: Source is lost after page refresh (f5)](https://github.com/playproject-io/play-ed/issues/15)
* [x] [`play-ed#16` - Uncaught (in promise) TypeError: object null is not iterable ... at getCompilerVersion](https://github.com/playproject-io/play-ed/issues/16)
* [ ] [`play-ed#1`: make autocomplete file explorer component](https://github.com/playproject-io/play-ed/issues/1)
* [ ] [`play-ed#14`: enable switching command/package versions](https://github.com/playproject-io/play-ed/issues/14)
* [ ] [`play-ed#12`: embeddable iframe-api](https://github.com/playproject-io/play-ed/issues/12)
* [ ] [`play-ed#13`: add solidity syntax highlighting for codemirror](https://github.com/playproject-io/play-ed/issues/13)
* [ ] preview multiple solidity contracts defined in one file
    * when multiple contracts in one file (show all, not just first one in separate tabs)
* [ ] manage multiple solidity (sample?) contract files
    * [ ] add more tabs with sample contracts? (think how would that work ui wise, maybe tabs, maybe file editor, maybe some third option)
* [ ] add workshop to teach how to use Play editor
* [ ] feature: copy the line (shift + control + D) 
* [ ] feature: move line (shift + control + arrows)
* [ ] feature: find in this file/all files (control + F/ shift + control + F)
* [ ] feature: create a string/array/object (double click and write single or double quote/open bracket, curly brace..) 
* [ ] feature: collapsing parts of the code (long functions etc.)
* [ ] [`play-ed#7`: enable url params](https://github.com/playproject-io/play-ed/issues/7)
* [ ] [`play-ed#8`: web console terminal](https://github.com/playproject-io/play-ed/issues/8)
* [ ] [`play-ed#9`: display compiler notification flags](https://github.com/playproject-io/play-ed/issues/9)
* [ ] [`play-ed#10`: make responsive (mobile first)](https://github.com/playproject-io/play-ed/issues/10)
* [ ] play editor features & refinements (e.g. ".js", ".html", ".sol", ...)
    * [x] plain design of the editor, embeddable in any style of pages/apps
    * [ ] feature: red dot after line number if compiler error (+ onhover details about error)
    * [ ] feature: color the lines where compiler error is
---
play editor features & refinement (e.g. SOL/JS/HTML/CSS/MD/... editor)
editor candies (copy selected lines, move lines, find in this file/all files)
not IDE, but EDITOR (only ethereum editor)

**concept**
- Editor
- Preview
  - function names
  - input fields
    - verification of inputs (ok or error icons - on hover shows what is error)
    - types (bool/int etc.)
- Connect with Metamask link (see [etherscan](https://etherscan.io/token/0x06012c8cf97bead5deae237070f9587f8e7a266d#writeContract))
- Extras (add-ons)
  - browse all extras
  - publish extras
  - add/remove || activate/deactivate extras
  - some extras are activated by default (custom for embedded play editor, if someone teaches testing, they can by default activate testing extras)
- Settings
  - show only what is needed (based on file type and based on plugins installed)
  - compiler version (dropdown or slider)
