### ISSUE TITLE
add & improve tiling window manager

### ISSUE THREAD

**Issue by serapath** [playproject-io/play-ed#4]
## `@todo`
* [x] fix styling bug
* [x] first draft can be non-resizable
* [x] remove left/right/both buttons
* [x] it splits the screen into `editor` (left), `contract ui` (right), `menu bar` (bottom)
* [ ] [`org-page#2`: Play brand book / design guide](https://github.com/playproject-io/playproject-io.github.io/issues/2)
* [ ] [`play-ed#3`: theme & styleguide](https://github.com/playproject-io/play-ed/issues/3)
* [ ] [`smartcontract.codes#5`: theme & styleguide](https://github.com/playproject-io/smartcontract.codes/issues/5)
* [ ] fix responsiveness
* [ ] extend the concept to make it more feature rich into a new issue
    * window manager" to coordinate layout and communication between parts of the play-editor and surrounding components (iframes?), also of different workshops, etc...
    * make window manager (changable layout)
* [ ] when you embed you can pre-define what will be collapsed/expanded in

---
