### ISSUE TITLE
display compiler notification flags

### ISSUE THREAD

**Issue by serapath** [playproject-io/play-ed#9]
## `@todo`
* [ ] connect compilation errors to editor line numbers (icon in the editor next to line number)
* [ ] show errors in play editor line numbers with icon indicators and more details on hover
* [ ] color the line(s) where the errors are present
* [ ] maybe keep a history log of compiler events including errors and warnings
* [ ] improve error messages

---
`solidity editor` display compilation errors/warnings and other indicators
